import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                {/* BackMor 11 Icon */}
                <link rel="icon" href="app/favicon.ico/"></link>
            </head>
            <body className={inter.className+" text-black "}>
                {children}
            </body>
        </html>
    );
}