import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "CPRE 888",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className="h-full">
      <div className="flex flex-col h-full">
        <main className="flex-grow">{children}</main>
      </div>
    </body>
  </html>
  );
}
