import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "BackMor",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                {/* BackMor 11 Icon */}
                <link rel="icon" href="/favicon.ico/"></link>
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
